name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.7, 3.8, 3.9, pypy2, pypy3]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # You can test your matrix by printing the current Python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Build
      run: |
        python -m pip install scons pytoml packaging
        scons -c
        scons
        python -m pip install dist/enscons*.whl
      
    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: dist
    #     path: ./dist
